SELECT FL.TITLE
FROM PUBLIC.FILM FL
LEFT JOIN PUBLIC.INVENTORY INV ON (FL.FILM_ID = INV.FILM_ID)
LEFT JOIN PUBLIC.RENTAL RENT ON (RENT.INVENTORY_ID = INV.INVENTORY_ID)
WHERE RENT.RENTAL_DATE >= '2005-05-24'
	AND RENT.RENTAL_DATE < '2005-05-25';