SELECT FL.TITLE
FROM PUBLIC.INVENTORY INV
LEFT JOIN PUBLIC.FILM FL ON (INV.FILM_ID = FL.FILM_ID)
LEFT JOIN PUBLIC.RENTAL RENT ON (RENT.INVENTORY_ID = INV.INVENTORY_ID)
WHERE RENT.INVENTORY_ID IS NULL;