SELECT FL.RELEASE_YEAR,
	FL.RATING,
	COUNT(FL.FILM_ID),
	COUNT(FL120.FILM_ID)
FROM FILM FL
LEFT JOIN FILM FL120 ON (FL120.FILM_ID = FL.FILM_ID
						 AND FL120.LENGTH >= 120)
GROUP BY FL.RELEASE_YEAR,
	FL.RATING;