WITH TOP_FILMS AS
	(SELECT FL.FILM_ID,
			FL.TITLE,
			SUM(PAY.AMOUNT) AS TOTALPAY
		FROM INVENTORY INV
		LEFT JOIN RENTAL RENT ON (RENT.INVENTORY_ID = INV.INVENTORY_ID)
		LEFT JOIN PAYMENT PAY ON (PAY.RENTAL_ID = RENT.RENTAL_ID)
		LEFT JOIN FILM FL ON (INV.FILM_ID = FL.FILM_ID)
		WHERE PAY.AMOUNT > 0
		GROUP BY FL.FILM_ID,
			FL.TITLE
		ORDER BY SUM(PAY.AMOUNT) DESC
		LIMIT 3)
SELECT ACT.FIRST_NAME,
	ACT.LAST_NAME,
	TP.TITLE,
	TP.TOTALPAY
FROM FILM_ACTOR FA
LEFT JOIN ACTOR ACT ON (ACT.ACTOR_ID = FA.ACTOR_ID)
RIGHT JOIN TOP_FILMS TP ON (TP.FILM_ID = FA.FILM_ID);